import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AppContextProvider } from "./context/Context.js"; 

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html data-theme = "dim" lang="en">
      <body>
      <AppContextProvider>
         {children}
      </AppContextProvider>
      </body>
    </html>
  )
}
